<?php

    return [
    'suggestions' => [
        [
            'key' => 'general.explain.topic',
            'text' => 'Can you explain this topic?',
            'category' => 'understanding',
            'audience' => ['kids', 'teens', 'adults'],
            'context' => ['general', 'instructor'],
            'active' => true,
            'display_order' => 10,
        ],
        [
            'key' => 'lesson.explain.topic',
            'text' => 'Can you explain this topic in simpler terms?',
            'category' => 'understanding',
            'audience' => ['kids', 'teens', 'adults'],
            'context' => ['lesson', 'general'],
            'active' => true,
            'display_order' => 20,
        ],
        [
            'key' => 'lesson.understand.section',
            'text' => 'Can you help me understand this lesson section?',
            'category' => 'understanding',
            'audience' => ['kids', 'teens', 'adults'],
            'context' => ['lesson', 'general'],
            'active' => true,
            'display_order' => 30,
        ],
        [
            'key' => 'module.review.next',
            'text' => 'What should I review next?',
            'category' => 'review',
            'audience' => ['kids', 'teens', 'adults'],
            'context' => ['module', 'general', 'instructor'],
            'active' => true,
            'display_order' => 40,
        ],
        [
            'key' => 'module.important.idea',
            'text' => 'What is an important idea to remember from this module?',
            'category' => 'review',
            'audience' => ['teens', 'adults'],
            'context' => ['module', 'general'],
            'active' => true,
            'display_order' => 50,
        ],
        [
            'key' => 'quiz.review.topic',
            'text' => 'Can you help me review the topic covered by this quiz?',
            'category' => 'review',
            'audience' => ['teens', 'adults'],
            'context' => ['quiz', 'lesson', 'general'],
            'active' => true,
            'display_order' => 60,
        ],
        [
            'key' => 'general.recommend.review',
            'text' => 'Can you recommend what I should review?',
            'category' => 'guidance',
            'audience' => ['teens', 'adults'],
            'context' => ['general', 'instructor'],
            'active' => true,
            'display_order' => 70,
        ],
    ],
];
